[package]
name = "yew-interactive"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
web-sys = { version = "0.3", features = ["HtmlInputElement"] }
